### ISSUE TITLE
ApiSever数据库添加id的md5值，并通过api暴露

### ISSUE THREAD

**Issue by ResTianTian** [HUCTF/2020-Works-ApiSecurity#42]
- [x] apiServer里改一下需要id是md5加密过的，并且需要提供一个接口来返回当前用户的id

**Comment by 99Kies** [comment]
url path:

/api/v1/show/id

请确保用户已经登入，超级用户账号密码默认为(admin, admin)

-----

通过``flask initdb --drop``重置数据库
